const dom = {
  dateLabel: document.getElementById("dateLabel"),
  tabs: document.querySelectorAll(".tab"),
  views: {
    day: document.getElementById("viewDay"),
    week: document.getElementById("viewWeek"),
    month: document.getElementById("viewMonth"),
    year: document.getElementById("viewYear"),
  },
  formPanel: document.getElementById("formPanel"),
  toggleFormBtn: document.getElementById("toggleFormBtn"),
  closeFormBtn: document.getElementById("closeFormBtn"),
  formStatus: document.getElementById("formStatus"),
  blobForm: document.getElementById("blobForm"),
  formTitle: document.getElementById("formTitle"),
  formSubmitBtn: document.getElementById("formSubmitBtn"),
  recurrenceType: document.getElementById("recurrenceType"),
  recurrenceSummary: document.getElementById("recurrenceSummary"),
  weeklyPerSlot: document.getElementById("weeklyPerSlot"),
  weeklySlots: document.getElementById("weeklySlots"),
  weeklySlotStatus: document.getElementById("weeklySlotStatus"),
  addWeeklySlotBtn: document.getElementById("addWeeklySlotBtn"),
  settingsBtn: document.getElementById("settingsBtn"),
  settingsPanel: document.getElementById("settingsPanel"),
  settingsModal: document.getElementById("settingsModal"),
  settingsBackdrop: document.getElementById("settingsBackdrop"),
  closeSettingsBtn: document.getElementById("closeSettingsBtn"),
  settingsForm: document.getElementById("settingsForm"),
  settingsStatus: document.getElementById("settingsStatus"),
  prevDayBtn: document.getElementById("prevDayBtn"),
  nextDayBtn: document.getElementById("nextDayBtn"),
  goTodayBtn: document.getElementById("goTodayBtn"),
  brandTitle: document.getElementById("brandTitle"),
  brandSubtitle: document.getElementById("brandSubtitle"),
  infoCard: document.getElementById("infoCard"),
  deleteRecurrenceBtn: document.getElementById("deleteRecurrenceBtn"),
  deleteOccurrenceBtn: document.getElementById("deleteOccurrenceBtn"),
};

export { dom };
